#!/usr/bin/env python3
"""Збирає Localizable.strings з нумерованого списку ключів і перекладів.

Ключі беруться ДОСЛІВНО з keys_uk.txt (виконавці-перекладачі їх не переписують),
переклади — з en_*.tsv за номером рядка. Так український текст неможливо зіпсувати.

Запуск з кореня репозиторію:
    python3 scripts/i18n/build_strings.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
I18N = os.path.join(ROOT, "scripts", "i18n")
APP = os.path.join(ROOT, "UkrainianVoicesApp", "App")

# Ключі, які втратили кирилицю після обгортання і тому не потрапляють у скан.
# Ключі, яких немає серед літералів у коді:
#  - "%@: %@." втратив кирилицю після обгортання і не потрапляє у скан;
#  - стать голосу приходить з манiфеста на сервері, а не з коду.
EXTRA_KEYS = ["%@: %@.", "чоловічий", "жіночий"]
EXTRA_EN = {
    "%@: %@.": "%@: %@.",
    "чоловічий": "male",
    "жіночий": "female",
}


def load_keys():
    p = os.path.join(I18N, "keys_uk.txt")
    with open(p, encoding="utf-8") as f:
        keys = [line.rstrip("\n") for line in f]
    return keys


def load_translations(count):
    out = {}
    for name in ("en_1.tsv", "en_2.tsv", "en_3.tsv"):
        p = os.path.join(I18N, name)
        if not os.path.exists(p):
            sys.exit("Немає файлу перекладу: %s" % p)
        with open(p, encoding="utf-8") as f:
            for line in f:
                line = line.rstrip("\n")
                if not line:
                    continue
                num, _, text = line.partition("\t")
                if not num.isdigit():
                    sys.exit("Зіпсований рядок у %s: %r" % (name, line[:60]))
                out[int(num)] = text
    missing = [i for i in range(1, count + 1) if i not in out]
    if missing:
        sys.exit("Немає перекладу для рядків: %s" % missing[:20])
    return out


def escape(text):
    """Екранує лише те, що ламає формат .strings. \\n у тексті вже екранований."""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\\\\n", "\\n")


def write_strings(path, pairs, header):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("/* %s */\n\n" % header)
        for key, value in pairs:
            f.write('"%s" = "%s";\n' % (escape(key), escape(value)))


def main():
    keys = load_keys()
    tr = load_translations(len(keys))
    en_pairs = [(k, tr[i + 1]) for i, k in enumerate(keys)]
    uk_pairs = [(k, k) for k in keys]
    for k in EXTRA_KEYS:
        en_pairs.append((k, EXTRA_EN[k]))
        uk_pairs.append((k, k))

    write_strings(os.path.join(APP, "en.lproj", "Localizable.strings"), en_pairs,
                  "RHVoice UA — English interface. Generated by scripts/i18n/build_strings.py")
    write_strings(os.path.join(APP, "uk.lproj", "Localizable.strings"), uk_pairs,
                  "RHVoice UA — українська. Ключ = текст. Потрібен, щоб система бачила підтримку української.")
    print("Записано %d ключів у en.lproj і uk.lproj" % len(en_pairs))


if __name__ == "__main__":
    main()
